#[build]
 # command = "npm install && npm start"
 # publish = "frontends"

#[[redirects]]
#  from = "/*"
 # to = "/"
 # status = 200

[build]
  command = "npm run build"
  publish = "frontends"
 
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
